### ISSUE TITLE
Change LICENSE from GPL-3.0 to MIT

### ISSUE THREAD

**Issue by jesopo** [jesopo/irctokens#3]
The goal of this project is simply to prevent as many people as possible from making simple mistakes around tokenisation of raw IRC data.

Given this, I'd like a much more permissive license.

GPL-3.0:
https://choosealicense.com/licenses/gpl-3.0/

MIT:
https://choosealicense.com/licenses/mit/

@aewens - given you are a contributor to this project, are you ok with this change?

**Comment by aewens** [comment]
I'd certainly okay with this, let's do it.
